[package]
name = "simple-ft"
version.workspace = true
edition.workspace = true

[dependencies]
sails.workspace = true
gstd.workspace = true
parity-scale-codec.workspace = true
scale-info.workspace = true